mongo:
  image: aashreys/mongo-auth
  volumes:
    - $HOME/data/mongodb:/data/db
  restart: always
  ports:
    - "27017:27017"
  environment:
    AUTH: "yes"
    MONGODB_ADMIN_USER: ${CCHECKS_MONGO_USER}
    MONGODB_ADMIN_PASS: ${CCHECKS_MONGO_PWD}
    MONGODB_APPLICATION_DATABASE: cchecksdb
    MONGODB_APPLICATION_USER: ${CCHECKS_MONGO_USER}
    MONGODB_APPLICATION_PASS: ${CCHECKS_MONGO_PWD}

mariadb:
  image: mariadb
  volumes:
    - $HOME/data/cchecks:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
  restart: always

redis:
  image: redis:latest
  restart: always
  volumes:
    - $HOME/data/redis:/data
  command:  redis-server --appendonly yes

sidekiq:
  build: .
  command: bundle exec sidekiq -r ./job.rb
  links:
    - redis
  environment:
    REDIS_HOST: redis
    SENDGRID_KEY: ${SENDGRID_KEY}

api:
  build: .
  ports:
    - "8834:8834"
  links:
    - mongo
    - mariadb
    - redis
    - sidekiq
  restart: always
  environment:
    CCHECKS_MONGO_USER: ${CCHECKS_MONGO_USER}
    CCHECKS_MONGO_PWD: ${CCHECKS_MONGO_PWD}
    CCHECKS_S3_WRITE_ACCESS_KEY: ${AWS_S3_WRITE_ACCESS_KEY}
    CCHECKS_S3_WRITE_SECRET_KEY: ${AWS_S3_WRITE_SECRET_KEY}
    SENDGRID_KEY: ${SENDGRID_KEY}
  volumes:
    - $HOME/tmp/htmls:/tmp/htmls
    - $HOME/tmp/mainthtmls:/tmp/mainthtmls
